### ISSUE TITLE
What license is this published under?

### ISSUE THREAD

**Issue by ttheuer** [waveOutReset/USB-SNES-Controller#1]
Love the concise and clever code, but I don't want to infringe on your copyrights, so if you could tell me what license it is published under, I'd be grateful!

**Comment by waveOutReset** [comment]
Sorry I forgot to write a license. This program is MIT license.

**Comment by ttheuer** [comment]
I hate to bring this up again, especially since I'm not at all sure about the details, but it seems like the `DigiJoystick.h` is licensed under the GPL, which would make your code GPL, too, I think?

I might be wrong, though.

**Comment by waveOutReset** [comment]
It turned out to be using the GPL license library.
I fixed about the license of the project.
Did this solve the problem?

**Comment by ttheuer** [comment]
Yes, thanks a lot!
